=== mirkovana/XML_i_Web_servisi_tim9/project/src/main/resources/documents/Obavestenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	targetNamespace="http://www.ftn.uns.ac.rs/obavestenje"
	xmlns:ob="http://www.ftn.uns.ac.rs/obavestenje">
	<xs:element name="obavestenje">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="opste_informacije" type="ob:Topste_informacije"> </xs:element>
				<xs:element name="naslov">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="podnaslov">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="telo" type="ob:Ttelo_obavestenja"> </xs:element>
				<xs:element name="dostavljeno">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Imenovanom"/>
							<xs:enumeration value="Arhivi"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="about" type="xs:string"/>
			<xs:attribute name="broj" type="ob:TBroj"/>
			<xs:attribute name="username" type="xs:string"/>
			<xs:attribute name="datum" type="ob:Tdatum"/>
			<xs:attribute name="poverenikUsername" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType abstract="true" name="Tadresa">
		<xs:sequence>
			<xs:element name="naziv_ulice">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="broj_ulice">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Tadresa_organa">
		<xs:complexContent>
			<xs:extension base="ob:Tadresa">
				<xs:sequence>
					<xs:element name="broj_kancelarije">
						<xs:simpleType>
							<xs:restriction base="xs:int">
								<xs:minInclusive value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Tadresa_podnosioca">
		<xs:complexContent>
			<xs:extension base="ob:Tadresa">
				<xs:sequence>
					<xs:element name="grad">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
								<xs:maxLength value="50"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="postanski_broj">
						<xs:simpleType>
							<xs:restriction base="xs:int">
								<xs:minInclusive value="11000"/>
								<xs:maxInclusive value="38999"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Ttelo_obavestenja" mixed="false">
		<xs:sequence>
			<xs:element name="godina" type="xs:gYear"/>
			<xs:element name="opis">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="1000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="datum" type="ob:Tdatum"/>
			<xs:element name="vreme" type="xs:time"/>
			<xs:element name="od" type="xs:time"/>
			<xs:element name="do" type="xs:time"/>
			<xs:element name="adresa_organa" type="ob:Tadresa_organa"/>
			<xs:element name="iznos">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="0"/>
						<xs:pattern value="[0-9]*.[0-9]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Torgan">
		<xs:sequence>
			<xs:element name="naziv">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="sediste">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Tpodnosilac">
		<xs:sequence>
			<xs:element name="ime">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="property" type="xs:string"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="prezime">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="property" type="xs:string"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="naziv_zahteva">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="adresa" type="ob:Tadresa_podnosioca"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Topste_informacije">
		<xs:sequence>
			<xs:element name="podaci_o_organu" type="ob:Torgan"/>
			<xs:element name="broj_predmeta">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="property" type="xs:string"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="datum">
				<xs:annotation>
					<xs:documentation>Datum formata dd.mm.yyyy.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ob:Tdatum">
							<xs:attribute name="property" type="xs:string"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="podaci_o_podnosiocu" type="ob:Tpodnosilac"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Tdatum">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{2}[.]\d{2}[.]\d{4}[.]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="datum" type="ob:Tdatum"/>
	<xs:simpleType name="TBroj">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}/[0-9]{4}-[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/project/src/main/resources/documents/Obavestenje1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ob:obavestenje xmlns:ob="http://www.ftn.uns.ac.rs/obavestenje" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/obavestenje Obavestenje.xsd ">
  <ob:opste_informacije>
    <ob:podaci_o_organu>
      <ob:naziv>ob:naziv</ob:naziv>
      <ob:sediste>ob:sediste</ob:sediste>
    </ob:podaci_o_organu>
    <ob:broj_predmeta property="">ob:broj_predmeta</ob:broj_predmeta>
    <ob:datum property="">ob:datum</ob:datum>
    <ob:podaci_o_podnosiocu>
      <ob:ime property="">ob:ime</ob:ime>
      <ob:prezime property="">ob:prezime</ob:prezime>
      <ob:naziv_zahteva>ob:naziv_zahteva</ob:naziv_zahteva>
      <ob:adresa>
        <ob:naziv_ulice>ob:naziv_ulice</ob:naziv_ulice>
        <ob:broj_ulice>ob:broj_ulice</ob:broj_ulice>
        <ob:grad>ob:grad</ob:grad>
        <ob:postanski_broj>0</ob:postanski_broj>
      </ob:adresa>
    </ob:podaci_o_podnosiocu>
  </ob:opste_informacije>
  <ob:naslov>ob:naslov</ob:naslov>
  <ob:podnaslov>ob:podnaslov</ob:podnaslov>
  <ob:telo>
    <ob:godina>2001</ob:godina>
    <ob:opis>ob:opis</ob:opis>
    <ob:datum>ob:datum</ob:datum>
    <ob:vreme>12:00:00</ob:vreme>
    <ob:od>12:00:00</ob:od>
    <ob:do>12:00:00</ob:do>
    <ob:adresa_organa>
      <ob:naziv_ulice>ob:naziv_ulice</ob:naziv_ulice>
      <ob:broj_ulice>ob:broj_ulice</ob:broj_ulice>
      <ob:broj_kancelarije>0</ob:broj_kancelarije>
    </ob:adresa_organa>
    <ob:iznos>0.0</ob:iznos>
  </ob:telo>
  <ob:dostavljeno>Imenovanom</ob:dostavljeno>
</ob:obavestenje>

=== mirkovana/XML_i_Web_servisi_tim9/project/src/main/resources/documents/obavestenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<ob:obavestenje xmlns:ob="http://www.ftn.uns.ac.rs/obavestenje" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/obavestenje Obavestenje.xsd ">
  <ob:opste_informacije>
    <ob:podaci_o_organu>
      <ob:naziv>Naziv organa</ob:naziv>
      <ob:sediste>Novi Sad</ob:sediste>
    </ob:podaci_o_organu>
    <ob:broj_predmeta>123abc</ob:broj_predmeta>
    <ob:datum>
      <ob:dan>---01</ob:dan>
      <ob:mesec>--01</ob:mesec>
      <ob:godina>2001</ob:godina>
    </ob:datum>
    <ob:podaci_o_podnosiocu>
      <ob:ime>Imenko</ob:ime>
      <ob:prezime>Prezimenko</ob:prezime>
      <ob:naziv_zahteva>Naziv_zahteva</ob:naziv_zahteva>
      <ob:adresa>
        <ob:naziv_ulice>Bul Despota Stefana</ob:naziv_ulice>
        <ob:broj_ulice>7</ob:broj_ulice>
        <ob:grad>Novi Sad</ob:grad>
        <ob:postanski_broj>21000</ob:postanski_broj>
      </ob:adresa>
    </ob:podaci_o_podnosiocu>
  </ob:opste_informacije>
  <ob:naslov>O B A V E S T E NJ E</ob:naslov>
  <ob:podnaslov>P O D N A S L O V</ob:podnaslov>
  <ob:telo>
    <ob:godina>2001</ob:godina>
    <ob:opis>Neki opis</ob:opis>
    <ob:datum>
      <ob:dan>---01</ob:dan>
      <ob:mesec>--01</ob:mesec>
      <ob:godina>2001</ob:godina>
    </ob:datum>
    <ob:vreme>12:00:00</ob:vreme>
    <ob:od>12:00:00</ob:od>
    <ob:do>12:00:00</ob:do>
    <ob:adresa_organa>
      <ob:naziv_ulice>Mire Popare</ob:naziv_ulice>
      <ob:broj_ulice>25</ob:broj_ulice>
      <ob:broj_kancelarije>12</ob:broj_kancelarije>
    </ob:adresa_organa>
    <ob:iznos>1200.00</ob:iznos>
  </ob:telo>
  <ob:dostavljeno>Imenovanom</ob:dostavljeno>
</ob:obavestenje>
