=== mirkovana/XML_i_Web_servisi_tim9/project/src/main/resources/documents/zalbanaodluku.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/zalbanaodluku"
    xmlns:zo="http://www.projekat.org/zalbanaodluku" xmlns:pred="http://www.projekat.org/predicate/">

    <xs:element name="zalba_na_odluku">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naslov">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="podaci_o_povereniku" type="zo:TPravno_lice"/>
                <xs:element name="podaci_o_zalbi" type="zo:Tpodaci_o_zalbi"/>
                <xs:element name="sadrzaj_zalbe" type="zo:Tsadrzaj_zalbe"/>
                <xs:element name="podaci_o_podnosiocu_zalbe" type="zo:TFizicko_lice"/>
                <xs:element name="podaci_o_mestu_i_datumu_podnosenja_zalbe" type="zo:Tmesto_datum"/>
                <xs:element name="napomena" type="zo:Tnapomena"/>
            </xs:sequence>
            <xs:attribute name="broj" type="zo:TBroj" use="required"/>
            <xs:attribute name="username" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="datum" type="zo:TDatum" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grad">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="zo:adresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="zo:TLice">
                <xs:sequence>
                    <xs:element name="naziv_poverenika">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="500"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="zo:TLice">
                <xs:sequence>
                    <xs:element name="ime">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="property" type="xs:string" use="optional"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="prezime">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="property" type="xs:string" use="optional"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="potpis">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="30"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="drugi_podaci_za_kontakt" minOccurs="0">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="50"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType mixed="true" name="Tpodaci_o_zalbi">
        <xs:sequence>
            <xs:element name="naslov">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="podnosilac_zalbe" type="zo:TFizicko_lice"/>
            <xs:element name="organ_koji_je_doneo_odluku">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="broj_zalbe">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="zo:TBroj">
                            <xs:attribute name="property" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="datum" type="zo:TDatum"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tsadrzaj_zalbe" mixed="true">
        <xs:sequence minOccurs="0">
            <xs:element name="datum" type="zo:TDatum" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="zbog_cega_se_pobija_odluka" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="500"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="predlog_povereniku" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tmesto_datum">
        <xs:sequence>
            <xs:element name="mesto">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="datum">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="zo:TDatum">
                            <xs:attribute name="property" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tnapomena">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="tacka">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TDatum">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}[.]"/>
            <xs:length value="11"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TBroj">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}/[0-9]{4}-[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/project/src/main/resources/documents/zalbanaodluku.xml
<?xml version="1.0" encoding="UTF-8"?>
<zo:zalba_na_odluku 
  xmlns="http://www.projekat.org/zalbanaodluku"
  xmlns:zo="http://www.projekat.org/zalbanaodluku"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.projekat.org/zalbanaodluku zalbanaodluku.xsd"
  username="username"
  datum="10.10.2010."
  broj="000-00-0000/0000-00">  
  <zo:naslov>  
    ŽALBA PROTIV ODLUKE ORGANA VLASTI KOJOM JE 
    ODBIJEN ILI ODBAČEN ZAHTEV ZA PRISTUP INFORMACIJI
  </zo:naslov>
  <zo:podaci_o_povereniku>
    <zo:adresa>
      <zo:grad>Beograd</zo:grad>
      <zo:ulica>Bulevar kralja</zo:ulica>
      <zo:broj>15</zo:broj>
    </zo:adresa>
    <zo:naziv_poverenika>Povereniku za informacije od javnog značaja i zaštitu podataka o ličnosti</zo:naziv_poverenika>
  </zo:podaci_o_povereniku>
  <zo:podaci_o_zalbi>
    <zo:naslov>ZALBA</zo:naslov>
    <zo:podnosilac_zalbe>
      <zo:adresa>
        <zo:grad>Novi Sad</zo:grad>
        <zo:ulica>ulicaneka</zo:ulica>
        <zo:broj>15</zo:broj>
      </zo:adresa>
      <zo:ime>Ime1</zo:ime>
      <zo:prezime>Prezime1</zo:prezime>
      <zo:potpis>Potpis1</zo:potpis>
    </zo:podnosilac_zalbe>
    protiv resenja-zakljucka
    <zo:organ_koji_je_doneo_odluku>
      orgaan koji je doneo odluku
    </zo:organ_koji_je_doneo_odluku>
    <zo:broj_zalbe>000-00-0000/0000-00</zo:broj_zalbe>
    <zo:datum>10.10.2010.</zo:datum>
  </zo:podaci_o_zalbi>
  <zo:sadrzaj_zalbe>
    Navedenom odlukom organa vlasti (rešenjem, zaključkom, obaveštenjem u pisanoj formi sa 
    elementima odluke) , suprotno zakonu, odbijen-odbačen je moj zahtev koji sam podneo/la-uputio/la
    dana <zo:datum>10.10.2010.</zo:datum> godine i tako mi uskraćeno-onemogućeno ostvarivanje ustavnog i zakonskog 
    prava na slobodan pristup informacijama od javnog značaja. Odluku pobijam u celosti, odnosno u 
    delu kojim
    <zo:zbog_cega_se_pobija_odluka>
      __________________ jer nije zasnovana na Zakonu o slobodnom pristupu informacijama od javnog značaja.
    </zo:zbog_cega_se_pobija_odluka>
    Na osnovu iznetih razloga, predlažem da 
    <zo:predlog_povereniku>
      Poverenik uvaži moju žalbu, poništi odluka 
      prvostepenog organa i omogući mi pristup traženoj/im informaciji/ma.      
    </zo:predlog_povereniku>
    Žalbu podnosim blagovremeno, u zakonskom roku utvrđenom u 
    članu 22. st. 1. Zakona o slobodnom pristupu informacijama od javnog značaja.
  </zo:sadrzaj_zalbe>
  <zo:podaci_o_podnosiocu_zalbe>
    <zo:adresa>
      <zo:grad>grad2</zo:grad>
      <zo:ulica>ulica2</zo:ulica>
      <zo:broj>10</zo:broj>
    </zo:adresa>
    <zo:ime>Ime1</zo:ime>
    <zo:prezime>Prezime1</zo:prezime>
    <zo:potpis>Potpis1</zo:potpis>
    <zo:drugi_podaci_za_kontakt>Drugipodaci</zo:drugi_podaci_za_kontakt>
  </zo:podaci_o_podnosiocu_zalbe>
  <zo:podaci_o_mestu_i_datumu_podnosenja_zalbe>
    <zo:mesto>Novi Sad</zo:mesto>
    <zo:datum>10.10.2010.</zo:datum>
  </zo:podaci_o_mestu_i_datumu_podnosenja_zalbe>
  <zo:napomena> 
    <zo:tacka>
      U žalbi se mora navesti odluka koja se pobija (rešenje, zaključak, obaveštenje), 
      naziv organa koji je odluku doneo, kao i broj i datum odluke. 
      Dovoljno je da žalilac navede u žalbi u kom pogledu je nezadovoljan odlukom,
      s tim da žalbu ne mora posebno obrazložiti. 
      Ako žalbu izjavljuje na ovom obrascu, dodatno obrazloženje može posebno priložiti.
    </zo:tacka>
    <zo:tacka>
      Uz žalbu obavezno priložiti kopiju podnetog zahteva i dokaz o njegovoj 
      predaji-upućivanju organu kao i kopiju odluke organa koja se osporava žalbom.
    </zo:tacka>
  </zo:napomena>
</zo:zalba_na_odluku>
