=== mirkovana/XML_i_Web_servisi_tim9/project/src/main/resources/documents/zalbazbogcutanja.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/zalbazbogcutanja"
    xmlns:zc="http://www.projekat.org/zalbazbogcutanja">
    <xs:element name="zalba_cutanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naslov">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="podaci_o_povereniku" type="zc:TPravno_lice"/>
                <xs:element name="telo_zalbe" type="zc:Ttelo_zalbe"/>
                <xs:element name="podaci_o_podnosiocu_zalbe" type="zc:TFizicko_lice"/>
                <xs:element name="podaci_o_mestu_i_datumu_podnosenja_zalbe" type="zc:Tmesto_datum"/>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="username" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="nazivOrgana" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grad">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="zc:adresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="zc:TLice">
                <xs:sequence>
                    <xs:element name="naziv_poverenika">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="500"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="zc:TLice">
                <xs:sequence>
                    <xs:element name="ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="2"/>
                                <xs:maxLength value="15"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="2"/>
                                <xs:maxLength value="20"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="drugi_podaci_za_kontakt">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="50"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="potpis">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType mixed="true" name="Ttelo_zalbe">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="zakon" maxOccurs="1" minOccurs="0" type="zc:TZakon"> </xs:element>
            <xs:element name="naziv_organa" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="razlozi" type="zc:Trazlozi" minOccurs="0"/>
            <xs:element name="datum" type="zc:TDatum" minOccurs="0"/>
            <xs:element name="podaci_o_zahtevu_i_informaciji" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="1000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="napomena" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tmesto_datum">
        <xs:sequence>
            <xs:element name="mesto">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="zc:TDatum"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Trazlozi">
        <xs:sequence>
            <xs:element maxOccurs="3" minOccurs="3" name="razlog">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute form="unqualified" name="podvuceno" type="xs:boolean"
                                use="required"/>
                            <xs:attribute form="unqualified" name="id" type="xs:int" use="required"
                            />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="nivoi">
        <xs:annotation>
            <xs:documentation>Tip koji predstalvja nivoe 1-6</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="6"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TDatum">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}[.]"/>
            <xs:length value="11"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TZakon">
        <xs:sequence>
            <xs:element minOccurs="0" name="clan" type="zc:TClan"> </xs:element>
            <xs:element minOccurs="0" name="stav" type="zc:TStav"> </xs:element>
            <xs:element minOccurs="0" name="tacka" type="zc:TNaziv"> </xs:element>
            <xs:element minOccurs="1" name="naziv" type="zc:TNaziv"> </xs:element>
            <xs:element minOccurs="0" name="glasnik" type="zc:TGlasnik"> </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TStav">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TClan">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TTacka">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TNaziv">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TGlasnik">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/out/zalbazbogcutanjaW.xml
<?xml version="1.0" encoding="UTF-8"?><zalba_cutanje xmlns="http://www.projekat.org/zalbazbogcutanja" xmlns:zc="http://www.projekat.org/zalbazbogcutanja" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.projekat.org/zalbazbogcutanja zalbazbogcutanja.xsd">
  <naslov zc:nivo="2" zc:stil="bold">ŽALBA KADA ORGAN VLASTI NIJE POSTUPIO/ nije postupio u celosti/ PO ZAHTEVU TRAŽIOCA U ZAKONSKOM ROKU (ĆUTANjE UPRAVE)</naslov>
  <podaci_o_povereniku>
    <adresa>
      <grad>Grad1</grad>
      <ulica>Ulica1</ulica>
      <broj>15</broj>
    </adresa>
    <naziv_poverenika>Povereniky za informacije od javnog značaja i zaštitu podataka o ličnosti</naziv_poverenika>
  </podaci_o_povereniku>
  <telo_zalbe>U skladu sa <zakon>
      <clan>članom 22.</clan>
      <naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</naziv>
    </zakon> podnosim: ZALBU protiv<naziv_organa>naziv organa</naziv_organa>zbog toga sto organ vlasti nije:<razlozi>
      <razlog id="1" podvuceno="false">nije postupio</razlog>
      <razlog id="2" podvuceno="false">nije postupio u celosti</razlog>
      <razlog id="3" podvuceno="false">nije postupio u zakonskom roku</razlog>
    </razlozi>po mom zahtevu za slobodan pristup informacijama od javnog značaja koji sam podneo tom organu dana<datum>10.10.2010.</datum>godine, a kojim sam tražio/la da mi se u skladu sa <zakon>
      <naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</naziv>
    </zakon>
    <podaci_o_zahtevu_i_informaciji>hasda hahda hsh adha adjhajda</podaci_o_zahtevu_i_informaciji>Na osnovu iznetog, predlažem da Poverenik uvaži moju žalbu i omogući mi pristup traženoj/im informaciji/ma. Kao dokaz , uz žalbu dostavljam kopiju zahteva sa dokazom o predaji organu vlasti<napomena>Kod žalbe zbog nepostupanju po zahtevu u celosti, treba priložiti i dobijeni odgovor organa vlasti.</napomena>
  </telo_zalbe>
  <podaci_o_podnosiocu_zalbe>
    <adresa>
      <grad>Grad2</grad>
      <ulica>Ulica2</ulica>
      <broj>10</broj>
    </adresa>
    <ime>Ime2</ime>
    <prezime>Prezime2</prezime>
    <drugi_podaci_za_kontakt>kjahdajbdkja podaci</drugi_podaci_za_kontakt>
    <potpis>potpis2</potpis>
  </podaci_o_podnosiocu_zalbe>
  <podaci_o_mestu_i_datumu_podnosenja_zalbe>
    <mesto>Mesto1</mesto>
    <datum>10.10.2010.</datum>
  </podaci_o_mestu_i_datumu_podnosenja_zalbe>
</zalba_cutanje>

=== mirkovana/XML_i_Web_servisi_tim9/project/src/main/resources/documents/zalbazbogcutanja.xml
<?xml version="1.0" encoding="UTF-8"?>
<zc:zalba_cutanje 
 broj="000-00-0000-0000-00" 
 id="0" 
 nazivOrgana="nazivOrgana" 
 username="username"
 xmlns ="http://www.projekat.org/zalbazbogcutanja"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xmlns:zc="http://www.projekat.org/zalbazbogcutanja"
 xmlns:pred="http://www.projekat.org/predicate/" 
 xsi:schemaLocation="http://www.projekat.org/zalbazbogcutanja zalbazbogcutanja.xsd ">
  <zc:broj xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:broj">000-00-0000-0000-00</zc:broj>
  <zc:naslov>zc:naslov</zc:naslov>
  <zc:podaci_o_povereniku>
    <zc:adresa>
      <zc:grad>zc:grad</zc:grad>
      <zc:ulica>zc:ulica</zc:ulica>
      <zc:broj>1</zc:broj>
    </zc:adresa>
    <zc:naziv_poverenika>zc:naziv_poverenika</zc:naziv_poverenika>
  </zc:podaci_o_povereniku>
  <zc:telo_zalbe>
    <zc:naziv_organa xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:organVlasti">zc:naziv_organa</zc:naziv_organa>
    <zc:razlozi>
      <zc:razlog id="0" podvuceno="true">zc:razlog</zc:razlog>
      <zc:razlog id="0" podvuceno="true">zc:razlog</zc:razlog>
      <zc:razlog id="0" podvuceno="true">zc:razlog</zc:razlog>
    </zc:razlozi>
    <zc:datum>10.10.2020.</zc:datum>
    <zc:podaci_o_zahtevu_i_informaciji>zc:podaci_o_zahtevu_i_informaciji</zc:podaci_o_zahtevu_i_informaciji>
  </zc:telo_zalbe>
  <zc:podaci_o_podnosiocu_zalbe>
    <zc:adresa>
      <zc:grad>zc:grad</zc:grad>
      <zc:ulica>zc:ulica</zc:ulica>
      <zc:broj>1</zc:broj>
    </zc:adresa>
    <zc:ime xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:ime">Imenic</zc:ime>
    <zc:prezime xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:prezime">Prezimic</zc:prezime>
    <zc:drugi_podaci_za_kontakt>zc:drugi_podaci_za_kontakt</zc:drugi_podaci_za_kontakt>
  </zc:podaci_o_podnosiocu_zalbe>
  <zc:podaci_o_mestu_i_datumu_podnosenja_zalbe>
    <zc:mesto xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:mesto">Mestasce</zc:mesto>
    <zc:datum xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:datum">10.11.2020.</zc:datum>
  </zc:podaci_o_mestu_i_datumu_podnosenja_zalbe>
</zc:zalba_cutanje>

=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/zalbazbogcutanjaE.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba_cutanje 
  xmlns="http://www.projekat.org/zalbazbogcutanja"
  xmlns:zc="http://www.projekat.org/zalbazbogcutanja"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.projekat.org/zalbazbogcutanja zalbazbogcutanja.xsd">
  <naslov zc:nivo="2" zc:stil="bold"> 
    ŽALBA KADA ORGAN VLASTI NIJE POSTUPIO/ nije 
    postupio u celosti/ PO ZAHTEVU TRAŽIOCA U ZAKONSKOM ROKU (ĆUTANjE UPRAVE)
  </naslov>
  <podaci_o_povereniku>
    <adresa>
      <grad></grad>
      <ulica></ulica>
      <broj></broj>
    </adresa>
    <naziv_poverenika>Povereniky za informacije od javnog značaja i zaštitu podataka o ličnosti</naziv_poverenika>
  </podaci_o_povereniku>
  <telo_zalbe>
    U skladu sa 
    <zakon>
      <clan>članom 22.</clan>
      <naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</naziv>
    </zakon>
    podnosim:
    ZALBU protiv
    <naziv_organa>
    </naziv_organa>
    zbog toga sto organ vlasti nije:
    <razlozi>
      <razlog podvuceno="false" id="1">nije postupio</razlog>
      <razlog podvuceno="false" id="2">nije postupio u celosti</razlog>
      <razlog podvuceno="false" id="3">u zakonskom roku</razlog>
    </razlozi>
    po mom zahtevu za slobodan pristup informacijama od javnog značaja koji sam podneo tom organu 
    dana <datum></datum> godine, a kojim sam tražio/la da mi se u skladu sa 
    <zakon> 
      <naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</naziv>
    </zakon>
    omogući uvid- kopija dokumenta koji sadrži informacije o /u vezi sa :
    <podaci_o_zahtevu_i_informaciji>
    </podaci_o_zahtevu_i_informaciji>
    Na osnovu iznetog, predlažem da Poverenik uvaži moju žalbu i 
    omogući mi pristup traženoj/im informaciji/ma.
    Kao dokaz , uz žalbu dostavljam kopiju zahteva sa dokazom o predaji organu vlasti
    <napomena>
      Kod žalbe zbog nepostupanju po zahtevu u celosti, treba priložiti i dobijeni odgovor organa vlasti.
    </napomena>
  </telo_zalbe>
  <podaci_o_podnosiocu_zalbe>
    <adresa>
      <grad></grad>
      <ulica></ulica>
      <broj></broj>
    </adresa>
    <ime></ime>
    <prezime></prezime>
    <drugi_podaci_za_kontakt></drugi_podaci_za_kontakt>
    <potpis></potpis>
  </podaci_o_podnosiocu_zalbe>
  <podaci_o_mestu_i_datumu_podnosenja_zalbe>
    <mesto></mesto>
    <datum></datum>
  </podaci_o_mestu_i_datumu_podnosenja_zalbe>
</zalba_cutanje>

=== mirkovana/XML_i_Web_servisi_tim9/organvlasti/src/main/resources/documents/zalbazbogcutanja.xml
<?xml version="1.0" encoding="UTF-8"?>
<zc:zalba_cutanje 
  xmlns="http://www.projekat.org/zalbazbogcutanja"
  xmlns:zc="http://www.projekat.org/zalbazbogcutanja"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:pred="http://www.projekat.org/predicate/"
  about="http://www.projekat.org/zalbazbogcutanja/aa54057c188c-2021"
  xsi:schemaLocation="http://www.projekat.org/zalbazbogcutanja zalbazbogcutanja.xsd" 
  broj="aa54057c188c-2021"
  username="username"
  nazivOrgana="nazivOrgana">
  <zc:broj xmlns:zc="http://www.projekat.org/zalbazbogcutanja" property="pred:broj">aa54057c188c-2021</zc:broj>
  <zc:telo_zalbe> 
    <zc:naziv_organa xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:organVlasti">
      naziv organa
    </zc:naziv_organa>
    <zc:razlozi>
      <zc:razlog podvuceno="false" id="1">nije postupio</zc:razlog>
      <zc:razlog podvuceno="false" id="2">nije postupio u celosti</zc:razlog>
      <zc:razlog podvuceno="false" id="3">u zakonskom roku</zc:razlog>
    </zc:razlozi>
    <zc:datum>10.10.2010.</zc:datum> 
    <zc:podaci_o_zahtevu_i_informaciji>
      hasda hahda hsh adha adjhajda
    </zc:podaci_o_zahtevu_i_informaciji>
  </zc:telo_zalbe>
  <zc:podaci_o_podnosiocu_zalbe>
    <zc:adresa>
      <zc:grad>Grad2</zc:grad>
      <zc:ulica>Ulica2</zc:ulica>
      <zc:broj>10</zc:broj>
    </zc:adresa>
    <zc:ime xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:ime">Ime2</zc:ime>
    <zc:prezime xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:prezime">Prezime2</zc:prezime>
    <zc:drugi_podaci_za_kontakt>kjahdajbdkja</zc:drugi_podaci_za_kontakt>
    <zc:potpis>potpis2</zc:potpis>
  </zc:podaci_o_podnosiocu_zalbe>
  <zc:podaci_o_mestu_i_datumu_podnosenja_zalbe>
    <zc:mesto xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:mesto">Mesto1</zc:mesto>
    <zc:datum xmlns:zc ="http://www.projekat.org/zalbazbogcutanja" property="pred:datum">10.10.2010.</zc:datum>
  </zc:podaci_o_mestu_i_datumu_podnosenja_zalbe>
</zc:zalba_cutanje>
