=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/out/resenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/resenje" xmlns:res="http://www.projekat.org/resenje">
    <xs:element name="zalba">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="uvod" type="res:TUvod"> </xs:element>
                <xs:element minOccurs="0" name="sadrzaj" type="res:TSadrzaj"/>
            </xs:sequence>
            <xs:attribute name="status" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TUvod">
        <xs:sequence>
            <xs:element name="broj">
                <xs:simpleType>
                    <xs:restriction base="res:TBroj">
                        <xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}/[0-9]{4}-[0-9]{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="res:TDatum"> </xs:element>
            <xs:element name="paragraf" type="res:TParagraf"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TSadrzaj">
        <xs:sequence>
            <xs:element name="resenje" minOccurs="1" type="res:TResenje"> </xs:element>
            <xs:element name="obrazlozenje" minOccurs="1" type="res:TObrazlozenje"> </xs:element>
            <xs:element minOccurs="1" name="poverenik" type="res:TOsoba"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOsoba">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="ime" nillable="false">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="prezime" nillable="false">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="datum" type="res:TDatum">
        <xs:annotation>
            <xs:documentation>Datum formata dd.mm.yyyy.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="naslov" type="res:TNaslov">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="TNaslov">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="res:nivo" use="required"/>
                <xs:attribute ref="res:stil" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:attribute name="nivo" type="res:nivoi">
        <xs:annotation>
            <xs:documentation>atribut koji predstavlja nivo naslova ili liste</xs:documentation>
        </xs:annotation>
    </xs:attribute>
    <xs:attribute name="stil" type="xs:string">
        <xs:annotation>
            <xs:documentation>atribut kojim se defini[e stil odre]eneog elementa</xs:documentation>
        </xs:annotation>
    </xs:attribute>
    <xs:simpleType name="nivoi">
        <xs:annotation>
            <xs:documentation>Tip koji predstalvja nivoe 1-6</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="6"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TZakon">
        <xs:sequence>
            <xs:element minOccurs="0" name="clan" type="res:TClan"> </xs:element>
            <xs:element minOccurs="0" name="stav" type="res:TStav"> </xs:element>
            <xs:element minOccurs="0" name="tacka" type="res:TTacka"> </xs:element>
            <xs:element minOccurs="1" name="naziv" type="res:TNaziv"> </xs:element>
            <xs:element minOccurs="0" name="glasnik" type="res:TGlasnik"> </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="TInstitucija">
        <xs:sequence>
            <xs:element name="naziv" type="res:TNaziv"> </xs:element>
            <xs:element name="mesto" type="res:TMesto"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="TParagraf">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element minOccurs="0" name="datum" type="res:TDatum"/>
            <xs:element minOccurs="0" name="institucija" type="res:TInstitucija">
                <xs:annotation>
                    <xs:documentation/>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="mesto" type="res:TMesto"/>
            <xs:element minOccurs="0" name="zakon" type="res:TZakon"> </xs:element>
            <xs:element minOccurs="0" name="osoba" type="res:TOsoba"/>
            <xs:element minOccurs="0" name="taksa" type="res:TTaksa"> </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TResenje">
        <xs:sequence>
            <xs:element ref="res:naslov"/>
            <xs:element maxOccurs="unbounded" name="paragraf" type="res:TParagraf"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TObrazlozenje">
        <xs:sequence>
            <xs:element ref="res:naslov"/>
            <xs:element maxOccurs="unbounded" name="paragraf" type="res:TParagraf"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TBroj">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}/[0-9]{4}-[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TDatum">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}[.]"/>
            <xs:length value="11"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TStav">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TClan">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TTacka">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TNaziv">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TGlasnik">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TTaksa">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TMesto">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/out/resenjeW.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba xmlns="http://www.projekat.org/resenje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" status="odbacena" 
 xsi:schemaLocation="http://www.projekat.org/resenje resenje.xsd">
  <uvod>
    <broj>123-45-6789/1011-12</broj>
    <datum>10.10.2010.</datum>
    <paragraf>Poverenik za informacije od javnog značaja i zaštitu podataka o ličnosti, u postupku po albi koju je izjavio<osoba>
        <ime>OsobaIme1</ime>
        <prezime>OsobaPrezime1</prezime>
      </osoba> zbog nepostupanja <institucija>
        <naziv>InstitucijaNaziv</naziv> u <mesto>InstitucijaMesto</mesto>
      </institucija>sa privremenim sedištem u <mesto>mesto sedista</mesto>po njegovom zahtevu od <datum>20.10.2010.</datum>godine za pristup informacijama od javnog značaja, na osnovu <zakon>
        <clan>člana 35.</clan>
        <stav>stav 1.</stav>
        <tacka>tacka 5</tacka>
        <naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</naziv>
        <glasnik>(„Sl. glasnik RS“, br. 120/04, 54/07, 104/09 i 36/10)</glasnik>
      </zakon>a u vezi sa <zakon>
        <clan>clanom 4.</clan>
        <tacka>tacka 22.</tacka>
        <naziv>Zakona o zaštiti podataka o ličnosti</naziv>
        <glasnik>(„Sl. glasnik RS“, broj 87/18)</glasnik>
      </zakon>kao i <zakon>
        <clan>člana 23. i člana 24.</clan>
        <stav>stav 4.</stav>
        <naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</naziv>
      </zakon>i<zakon>
        <clan>clana 173.</clan>
        <stav>stav2.</stav>
        <naziv>Zakona o opštem upravnom postupku</naziv>
        <glasnik>(„Sl. glasnik RS“, br. 18/2016 i 95/2018-autentično tumačenje)</glasnik>
      </zakon>, donosi:</paragraf>
  </uvod>
  <sadrzaj>
    <resenje>
      <naslov naslov="2">RESENJE</naslov>
      <paragraf>Nalaže se <institucija>
          <naziv>Učiteljskom fakultetu</naziv> u <mesto>Prizrenu</mesto>
        </institucija>sa privremenim sedištem u <mesto>Leposaviću</mesto>, da bez odlaganja, a najkasnije u roku od pet dana od dana prijema ovog rešenja, obavesti <osoba>
          <ime>A</ime>
          <prezime>A</prezime>
        </osoba>, da li poseduje tražene informacije odnosno dokument u kome su iste sadržane, i to: Ugovor o radu koji je kao poslednji potpisan između  tog Fakulteta i <osoba>
          <ime>C</ime>
          <prezime>C</prezime>
        </osoba>, te da mu, ukoliko takav dokument poseduje dostavi kopiju istog elektronskom poštom na adresu … ili poštom,</paragraf>
      <paragraf>II O izvršenju rešenja <institucija>
          <naziv>Učiteljski fakultet</naziv> u <mesto>Prizrenu</mesto>
        </institucija>sa privremenim sedištem u <mesto>Leposaviću</mesto>, će obavestiti Poverenika u roku od sedam dana od prijema ovog rešenja.</paragraf>
    </resenje>
    <obrazlozenje>
      <naslov naslov="2">OBRAZLOZENJE</naslov>
      <paragraf>
        <osoba>
          <ime>A</ime>
          <prezime>A</prezime>
        </osoba>, kao tražilac informacija, izjavio je dana <datum>07.05.2020.</datum>godine žalbu Povereniku, zbog nepostupanja <institucija>
          <naziv>Učiteljskog fakulteta</naziv> u <mesto>Prizrenu</mesto>
        </institucija>sa privremenim sedištem u <mesto>Leposavicu</mesto>po njegovom zahtevu od <datum>16.04.2020.</datum>godine za pristup informacijama od javnog značaja i u prilogu dostavio kopiju istog.</paragraf>
      <paragraf>Protiv ovog rešenja nije dopuštena žalba već se, u skladu sa <zakon>
          <naziv>Zakonom o upravnim sporovima</naziv>
        </zakon>, može pokrenuti upravni spor tužbom <institucija>
          <naziv>Upravnom sudu</naziv> u <mesto>Beogradu</mesto>
        </institucija>u roku od 30 dana od dana prijema rešenja. Taksa na tužbu iznosi <taksa>390.00</taksa>dinara</paragraf>
    </obrazlozenje>
    <poverenik>
      <ime>ImePoverenika</ime>
      <prezime>PrezimePoverenika</prezime>
    </poverenik>
  </sadrzaj>
</zalba>

=== mirkovana/XML_i_Web_servisi_tim9/project/src/main/resources/documents/resenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<res:zalba
    xmlns ="http://www.projekat.org/resenje"
    xmlns:res="http://www.projekat.org/resenje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.projekat.org/predicate/"
    about="http://www.projekat.org/resenje/000-00-0000/0000-00"
    xsi:schemaLocation="http://www.projekat.org/resenje resenje.xsd"
    status="osnovana"
    broj="000-00-0000/0000-00"
    username="username"
    datum="00.00.0000."
    poverenikUsername="poverenikUsername">
    <res:broj xmlns:res ="http://www.projekat.org/resenje" property="pred:broj">000-00-0000/0000-00</res:broj>
    <res:status xmlns:res ="http://www.projekat.org/resenje" property="pred:status">osnovana</res:status>
    <res:uvod>
        <res:paragraf>
            Poverenik za informacije od javnog značaja i zaštitu
            podataka o ličnosti, u postupku po zalbi koju je izjavio
            <res:osoba>
                <res:ime  xmlns:res ="http://www.projekat.org/resenje" property="pred:osobaIme">A</res:ime>
                <res:prezime  xmlns:res ="http://www.projekat.org/resenje" property="pred:osobaPrezime">A</res:prezime>
            </res:osoba> 
            zbog nepostupanja
            <res:institucija> 
                <res:naziv xmlns:res ="http://www.projekat.org/resenje" property="pred:institucijaNaziv">Učiteljskog fakulteta</res:naziv> 
                u <res:mesto>Prizrenu</res:mesto>
            </res:institucija>
            sa privremenim sedištem u 
            <res:mesto>Leposaviću, ul. Nemanjina bb</res:mesto>, 
            po njegovom zahtevu od 
            <res:datum xmlns:res ="http://www.projekat.org/resenje" property="pred:datum">16.04.2020.</res:datum> 
            godine za pristup informacijama od javnog značaja, na osnovu 
            <res:zakon>
                <res:clan>člana 35.</res:clan>
                <res:stav>stav 1.</res:stav>
                <res:tacka>tačka 5.</res:tacka>
                <res:naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</res:naziv>
                <res:glasnik>(„Sl. glasnik RS“, br. 120/04, 54/07, 104/09 i 36/10)</res:glasnik>
            </res:zakon> 
            a u vezi sa 
            <res:zakon>
                <res:clan>članom 4.</res:clan>
                <res:tacka>tačka 22.</res:tacka>
                <res:naziv>Zakona o zaštiti podataka o ličnosti</res:naziv>
                <res:glasnik>(„Sl. glasnik RS“, broj 87/18)</res:glasnik>
            </res:zakon>
            kao i 
            <res:zakon>
                <res:clan>člana 23. i člana 24.</res:clan>
                <res:stav>stav 4.</res:stav>
                <res:naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</res:naziv>
            </res:zakon>
            i
            <res:zakon>
                <res:clan>člana 173.</res:clan>
                <res:stav>stav 2.</res:stav>
                <res:naziv>Zakona o opštem upravnom postupku</res:naziv>
                <res:glasnik>(„Sl. glasnik RS“, br. 18/2016 i 95/2018-autentično tumačenje)</res:glasnik>
            </res:zakon>
            , donosi
        </res:paragraf>
    </res:uvod>
    <res:sadrzaj>
        <res:resenje>
            <res:naslov>RESENJE</res:naslov>
            <res:paragraf>
                Nalaže se 
                <res:institucija>
                    <res:naziv>Učiteljskom fakultetu</res:naziv> u
                    <res:mesto>Prizrenu</res:mesto>
                </res:institucija>
                sa privremenim sedištem u 
                <res:mesto>Leposaviću</res:mesto>
                , da bez odlaganja, a najkasnije u roku od pet dana od dana prijema 
                ovog rešenja, obavesti 
                <res:osoba><res:ime>A</res:ime><res:prezime>A</res:prezime></res:osoba>
                , da li poseduje tražene informacije odnosno dokument u kome su iste 
                sadržane, i to: <res:trazena_informacija xmlns:res ="http://www.projekat.org/resenje" property="pred:trazena_informacija">Ugovor o radu</res:trazena_informacija> 
                koji je kao poslednji potpisan između tog Fakulteta i 
                <res:osoba><res:ime>B</res:ime><res:prezime>B</res:prezime></res:osoba>
                , te da mu, ukoliko takav dokument poseduje dostavi kopiju
                istog elektronskom poštom na adresu … ili poštom,
                s tim što će pre dostavljanja zaštititi i učiniti nedostupnim
                podatke o ličnosti kojima bi se povredilo pravo na privatnost
                lica na koje se informacije odnose, kao što su: 
                adresa stanovanja, lični matični broj građana, ime oca, radni staž,
                prosečna ocena studiranja i sl. ukoliko su takvi podaci sadržani
                u traženom dokumentu.
            </res:paragraf>
            <res:paragraf>
                II O izvršenju rešenja 
                <res:institucija>
                    <res:naziv>Učiteljski fakultet</res:naziv> u 
                    <res:mesto>Prizrenu</res:mesto>
                </res:institucija>
                sa privremenim sedištem u 
                <res:mesto>Leposaviću</res:mesto>
                , će obavestiti Poverenika u roku od sedam dana od prijema ovog rešenja.
            </res:paragraf>
        </res:resenje>
        <res:obrazlozenje>
            <res:naslov>OBRAZLOZENJE</res:naslov>
            <res:paragraf> 
                <res:osoba><res:ime>A</res:ime><res:prezime>A</res:prezime></res:osoba>
                , kao tražilac informacija, izjavio je dana 
                <res:datum>07.05.2020.</res:datum>
                godine žalbu Povereniku, zbog nepostupanja 
                <res:institucija>
                    <res:naziv>Učiteljskog fakulteta</res:naziv>u
                    <res:mesto>Prizrenu</res:mesto>
                </res:institucija>
                sa privremenim sedištem u 
                <res:mesto>Leposaviću</res:mesto>
                po njegovom zahtevu od
                <res:datum>16.04.2020.</res:datum>
                godine za pristup informacijama od javnog značaja i u prilogu dostavio kopiju istog.
            </res:paragraf>
            <res:paragraf>
                Protiv ovog rešenja nije dopuštena žalba već se, u skladu sa 
                <res:zakon>
                    <res:naziv>Zakonom o upravnim sporovima</res:naziv>
                </res:zakon>
                , može pokrenuti upravni spor tužbom 
                <res:institucija>
                    <res:naziv>Upravnom sudu</res:naziv> u 
                    <res:mesto>Beogradu</res:mesto>
                </res:institucija>
                u roku od 30 dana od dana prijema rešenja. 
                Taksa na tužbu iznosi <res:taksa>390.00</res:taksa>dinara.
            </res:paragraf>
        </res:obrazlozenje>
        <res:poverenik>
            <res:ime xmlns:res ="http://www.projekat.org/resenje" property="pred:poverenikIme">IME</res:ime>
            <res:prezime xmlns:res ="http://www.projekat.org/resenje" property="pred:poverenikPrezime">PREZIME</res:prezime>
        </res:poverenik>
    </res:sadrzaj>
</res:zalba>
