=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/out/zalbanaodluku.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/zalbanaodluku"
    xmlns:zo="http://www.projekat.org/zalbanaodluku">

    <xs:element name="zalba_na_odluku">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naslov" type="zo:TNaslov"> </xs:element>
                <xs:element name="podaci_o_povereniku" type="zo:TPravno_lice"/>
                <xs:element name="podaci_o_zalbi" type="zo:Tpodaci_o_zalbi"/>
                <xs:element name="sadrzaj_zalbe" type="zo:Tsadrzaj_zalbe"/>
                <xs:element name="podaci_o_podnosiocu_zalbe" type="zo:TFizicko_lice"/>
                <xs:element name="podaci_o_mestu_i_datumu_podnosenja_zalbe" type="zo:Tmesto_datum"/>
                <xs:element name="napomena" type="zo:Tnapomena"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grad">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="zo:adresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="zo:TLice">
                <xs:sequence>
                    <xs:element name="naziv_poverenika">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="500"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="zo:TLice">
                <xs:sequence>
                    <xs:element name="ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="2"/>
                                <xs:maxLength value="15"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="2"/>
                                <xs:maxLength value="20"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="potpis">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="30"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="drugi_podaci_za_kontakt" minOccurs="0">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="50"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType mixed="true" name="Tpodaci_o_zalbi">
        <xs:sequence>
            <xs:element name="naslov" type="zo:TNaslov"> </xs:element>
            <xs:element name="podnosilac_zalbe" type="zo:TFizicko_lice"/>
            <xs:element name="organ_koji_je_doneo_odluku">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj_zalbe">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}/[0-9]{4}-[0-9]{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="zo:TDatum"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tsadrzaj_zalbe" mixed="true">
        <xs:sequence minOccurs="0">
            <xs:element name="datum" type="zo:TDatum" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="zbog_cega_se_pobija_odluka" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="500"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="predlog_povereniku" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tmesto_datum">
        <xs:sequence>
            <xs:element name="mesto">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="zo:TDatum"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tnapomena">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="tacka">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TNaslov">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="zo:nivo" use="required"/>
                <xs:attribute ref="zo:stil" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:attribute name="nivo" type="zo:nivoi">
        <xs:annotation>
            <xs:documentation>atribut koji predstavlja nivo naslova ili liste</xs:documentation>
        </xs:annotation>
    </xs:attribute>
    <xs:attribute name="stil" type="xs:string">
        <xs:annotation>
            <xs:documentation>atribut kojim se defini[e stil odre]eneog elementa</xs:documentation>
        </xs:annotation>
    </xs:attribute>
    <xs:simpleType name="nivoi">
        <xs:annotation>
            <xs:documentation>Tip koji predstalvja nivoe 1-6</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="6"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TDatum">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}[.]"/>
            <xs:length value="11"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/organvlasti/src/main/resources/documents/zalbanaodluku.xml
<?xml version="1.0" encoding="UTF-8"?>
<zo:zalba_na_odluku 
  xmlns="http://www.projekat.org/zalbanaodluku"
  xmlns:zo="http://www.projekat.org/zalbanaodluku"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:pred="http://www.projekat.org/predicate/"
  about="http://www.projekat.org/zalbanaodluku/aa54057c188c-2021"
  xsi:schemaLocation="http://www.projekat.org/zalbanaodluku zalbanaodluku.xsd"
  username="username"
  datum="10.10.2010."
  broj="aa54057c188c-2021">
  <zo:podaci_o_zalbi>
    <zo:podnosilac_zalbe>
      <zo:adresa>
        <zo:grad>Novi Sad</zo:grad>
        <zo:ulica>ulicaneka</zo:ulica>
        <zo:broj>15</zo:broj>
      </zo:adresa>
      <zo:ime>Ime1</zo:ime>
      <zo:prezime>Prezime1</zo:prezime>
      <zo:potpis>Potpis1</zo:potpis>
    </zo:podnosilac_zalbe>
    <zo:organ_koji_je_doneo_odluku xmlns:zo ="http://www.projekat.org/zalbanaodluku" property="pred:organVlasti">
      orgaan koji je doneo odluku 
    </zo:organ_koji_je_doneo_odluku>
    <zo:broj_zalbe xmlns:zo ="http://www.projekat.org/zalbanaodluku" property="pred:broj">aa54057c188c-2021</zo:broj_zalbe>
    <zo:datum>10.10.2010.</zo:datum>
  </zo:podaci_o_zalbi>
  <zo:sadrzaj_zalbe>
    <zo:datum>10.10.2010.</zo:datum> 
    <zo:zbog_cega_se_pobija_odluka>razlog</zo:zbog_cega_se_pobija_odluka> 
  </zo:sadrzaj_zalbe>
  <zo:podaci_o_podnosiocu_zalbe>
    <zo:adresa>
      <zo:grad>grad2</zo:grad>
      <zo:ulica>ulica2</zo:ulica>
      <zo:broj>10</zo:broj>
    </zo:adresa>
    <zo:ime xmlns:zo ="http://www.projekat.org/zalbanaodluku" property="pred:ime">Ime1</zo:ime>
    <zo:prezime xmlns:zo ="http://www.projekat.org/zalbanaodluku" property="pred:prezime">Prezime1</zo:prezime>
    <zo:potpis>Potpis1</zo:potpis>
    <zo:drugi_podaci_za_kontakt>Drugipodaci</zo:drugi_podaci_za_kontakt>
  </zo:podaci_o_podnosiocu_zalbe>
  <zo:podaci_o_mestu_i_datumu_podnosenja_zalbe>
    <zo:mesto xmlns:zo ="http://www.projekat.org/zalbanaodluku" property="pred:mesto">Novi Sad</zo:mesto>
    <zo:datum xmlns:zo ="http://www.projekat.org/zalbanaodluku" property="pred:datum">10.10.2010.</zo:datum>
  </zo:podaci_o_mestu_i_datumu_podnosenja_zalbe>
</zo:zalba_na_odluku>

=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/zalbanaodlukuE.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba_na_odluku 
  xmlns="http://www.projekat.org/zalbanaodluku"
  xmlns:zalba="http://www.projekat.org/zalbanaodluku"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.projekat.org/zalbanaodluku zalbanaodluku.xsd">  
  <naslov zalba:nivo="2" zalba:stil="bold">
    ŽALBA PROTIV ODLUKE ORGANA VLASTI KOJOM JE
    ODBIJEN ILI ODBAČEN ZAHTEV ZA PRISTUP INFORMACIJI
  </naslov>
  <podaci_o_povereniku>
    <adresa>
      <grad></grad>
      <ulica></ulica>
      <broj></broj>
    </adresa>
    <naziv_poverenika>Povereniku za informacije od javnog značaja i zaštitu podataka o ličnosti</naziv_poverenika>
  </podaci_o_povereniku>
  <podaci_o_zalbi>
    <naslov zalba:nivo="2">ZALBA</naslov>
    <podnosilac_zalbe>
      <adresa>
        <grad></grad>
        <ulica></ulica>
        <broj></broj>
      </adresa>
      <ime></ime>
      <prezime></prezime>
      <potpis></potpis>
    </podnosilac_zalbe>
    protiv resenja-zakljucka
    <organ_koji_je_doneo_odluku>
    </organ_koji_je_doneo_odluku>
    <broj_zalbe></broj_zalbe>
    <datum></datum>
  </podaci_o_zalbi>
  <sadrzaj_zalbe>
    Navedenom odlukom organa vlasti (rešenjem, zaključkom, obaveštenjem u pisanoj formi sa 
    elementima odluke) , suprotno zakonu, odbijen-odbačen je moj zahtev koji sam podneo/la-uputio/la
    dana <datum></datum> godine i tako mi uskraćeno-onemogućeno ostvarivanje ustavnog i zakonskog 
    prava na slobodan pristup informacijama od javnog značaja. Odluku pobijam u celosti, odnosno u 
    delu kojim
    <zbog_cega_se_pobija_odluka>
    </zbog_cega_se_pobija_odluka>
    Na osnovu iznetih razloga, predlažem da 
    <predlog_povereniku>  
    </predlog_povereniku>
    Žalbu podnosim blagovremeno, u zakonskom roku utvrđenom u 
    članu 22. st. 1. Zakona o slobodnom pristupu informacijama od javnog značaja.
  </sadrzaj_zalbe>
  <podaci_o_podnosiocu_zalbe>
    <adresa>
      <grad></grad>
      <ulica></ulica>
      <broj></broj>
    </adresa>
    <ime></ime>
    <prezime></prezime>
    <potpis></potpis>
  </podaci_o_podnosiocu_zalbe>
  <podaci_o_mestu_i_datumu_podnosenja_zalbe>
    <mesto></mesto>
    <datum></datum>
  </podaci_o_mestu_i_datumu_podnosenja_zalbe>
  <napomena>
    <tacka>
      U žalbi se mora navesti odluka koja se pobija (rešenje, zaključak, obaveštenje), 
      naziv organa koji je odluku doneo, kao i broj i datum odluke. 
      Dovoljno je da žalilac navede u žalbi u kom pogledu je nezadovoljan odlukom,
      s tim da žalbu ne mora posebno obrazložiti. 
      Ako žalbu izjavljuje na ovom obrascu, dodatno obrazloženje može posebno priložiti.
    </tacka>
    <tacka>
      Uz žalbu obavezno priložiti kopiju podnetog zahteva i dokaz o njegovoj 
      predaji-upućivanju organu kao i kopiju odluke organa koja se osporava žalbom.
    </tacka>
  </napomena>
</zalba_na_odluku>
