=== mirkovana/XML_i_Web_servisi_tim9/projectsoap/src/main/resources/documents/explanation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/explanation"
    xmlns:ex="http://www.projekat.org/explanation" xmlns:pred="http://www.projekat.org/predicate/">

    <xs:element name="explanation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="broj">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="username">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="organVlastiUsername">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="text" type="xs:string"/>
                <xs:element name="mesto" type="xs:string"/>
                <xs:element name="datum">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ime" type="xs:string"/>
                <xs:element name="prezime" type="xs:string"/>
                <xs:element name="potpis" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="broj" type="xs:string" use="required"/>
            <xs:attribute name="tipZalbe" type="xs:string" use="required"/>
            <xs:attribute name="username" type="xs:string" use="required"/>
            <xs:attribute name="organVlastiUsername" type="xs:string" use="required"/>
            <xs:attribute name="about" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/projectsoap/src/main/resources/documents/explanation.xml
<?xml version="1.0" encoding="UTF-8"?>
<ex:explanation 
    xmlns:ex="http://www.projekat.org/explanation"
    xmlns:pred="http://www.projekat.org/predicate/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    
    xsi:schemaLocation="http://www.projekat.org/explanation explanation.xsd"
    broj="broj0" 
    tipZalbe="tipZalbe0"
    username="username0"
    organVlastiUsername="organVlastiUsername0" 
    about="http://www.projekat.org/explanation/aa54057c188c-2021">
    <ex:broj property="pred:broj">aa54057c188c-2021</ex:broj>
    <ex:username property="pred:username">username0</ex:username>
    <ex:organVlastiUsername property="pred:organVlastiUsername">organVlastiUsername0</ex:organVlastiUsername>
    <ex:text>dashdkjahdadakdjhadkajhdahjkdhakj</ex:text>
    <ex:mesto>mesto</ex:mesto>
    <ex:datum property="pred:datum">10.10.2010.</ex:datum>
    <ex:ime>ime</ex:ime>
    <ex:prezime>prezime</ex:prezime>
    <ex:potpis>potpis</ex:potpis>
</ex:explanation>
