=== mirkovana/XML_i_Web_servisi_tim9/projectsoap/src/main/resources/documents/izvestaj.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="izvestaj">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zahtevi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="brojPodnetih" type="xs:int"/>
                            <xs:element name="brojUsvojenih" type="xs:int"/>
                            <xs:element name="brojOdbacenih" type="xs:int"/>
                            <xs:element name="brojOdbijenih" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="zalbe">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="brojPodnetih" type="xs:int"/>
                            <xs:element name="brojZbogNepostupanja" type="xs:int"/>
                            <xs:element name="brojZbogOdbijanja" type="xs:int"/>
                            <xs:element name="brojNaZakljucakOdbacivanju" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="datum" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/demo/data/izvestaj.xml
<?xml version="1.0" encoding="UTF-8"?>
<izvestaj xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="./izvestaj.xsd">
    <zahtevi>
        <brojPodnetih>0</brojPodnetih> 
        <brojUsvojenih>0</brojUsvojenih>
        <brojOdbacenih>0</brojOdbacenih>
        <brojOdbijenih>0</brojOdbijenih>
    </zahtevi>
    <zalbe>
        <brojPodnetih>0</brojPodnetih>
        <brojZbogNepostupanja>0</brojZbogNepostupanja>
        <brojZbogOdbijanja>0</brojZbogOdbijanja>
        <brojNaZakljucakOdbacivanju>0</brojNaZakljucakOdbacivanju>
    </zalbe>
</izvestaj>

=== mirkovana/XML_i_Web_servisi_tim9/demo/data/izvestaj1.xml
<?xml version="1.0" encoding="UTF-8"?>
<izvestaj xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/2020/XML/projekatgit/XML_i_Web_servisi_tim9/demo/data/izvestaj.xsd" id="id0" datum="datum0">
    <zahtevi>
        <brojPodnetih>0</brojPodnetih>
        <brojUsvojenih>0</brojUsvojenih>
        <brojOdbacenih>0</brojOdbacenih>
        <brojOdbijenih>0</brojOdbijenih>
    </zahtevi>
    <zalbe>
        <brojPodnetih>0</brojPodnetih>
        <brojZbogNepostupanja>0</brojZbogNepostupanja>
        <brojZbogOdbijanja>0</brojZbogOdbijanja>
        <brojNaZakljucakOdbacivanju>0</brojNaZakljucakOdbacivanju>
    </zalbe>
</izvestaj>
