=== mirkovana/XML_i_Web_servisi_tim9/demo/data/Obavestenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://www.obavestenje.rs" xmlns:obavestenje="https://www.obavestenje.rs">

    <xs:element name="obavestenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="opste_informacije">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="podaci_o_organu">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv" type="xs:string"/>
                                        <xs:element name="sediste" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="broj_predmeta" type="xs:string"/>
                            <xs:element ref="obavestenje:datum"/>
                            <xs:element name="podaci_o_podnosiocu">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ime" type="xs:string"/>
                                        <xs:element name="prezime" type="xs:string"/>
                                        <xs:element name="naziv" type="xs:string"/>
                                        <xs:element name="adresa">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="ulica" type="xs:string"/>
                                                  <xs:element name="broj_ulice" type="xs:string"/>
                                                  <xs:element name="grad" type="xs:string"/>
                                                  <xs:element name="postanski_broj">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:integer">
                                                  <xs:minInclusive value="1"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="naslov" type="xs:string"/>
                <xs:element name="podnaslov" type="xs:string"/>
                <xs:element name="telo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="godina" type="xs:gYear"/>
                            <xs:element name="opis" type="xs:string"/>
                            <xs:element ref="obavestenje:datum"/>
                            <xs:element name="vreme" type="xs:time"/>
                            <xs:element name="od" type="xs:time"/>
                            <xs:element name="do" type="xs:time"/>
                            <xs:element name="adresa_organa">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="naziv_ulice" type="xs:string"/>
                                        <xs:element name="broj_ulice" type="xs:string"/>
                                        <xs:element name="broj_kancelarije">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="iznos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dostavljeno">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Imenovanom"/>
                            <xs:enumeration value="Arhivi"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="datum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dan" type="xs:gDay"/>
                <xs:element name="mesec" type="xs:gMonth"/>
                <xs:element name="godina" type="xs:gYear"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/demo/data/Obavestenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<ob:obavestenje xmlns:ob="http://www.ftn.uns.ac.rs/obavestenje" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/obavestenje Obavestenje.xsd ">
  <ob:opste_informacije>
    <ob:podaci_o_organu>
      <ob:naziv>Neki organ</ob:naziv>
      <ob:sediste>Novi Sad</ob:sediste>
    </ob:podaci_o_organu>
    <ob:broj_predmeta>123abc</ob:broj_predmeta>
    <ob:datum>
      <ob:dan>---01</ob:dan>
      <ob:mesec>--01</ob:mesec>
      <ob:godina>2001</ob:godina>
    </ob:datum>
    <ob:podaci_o_podnosiocu>
      <ob:ime>Imenko</ob:ime>
      <ob:prezime>Prezimenko</ob:prezime>
      <ob:naziv_zahteva>Zahteva za nesto</ob:naziv_zahteva>
      <ob:adresa>
        <ob:naziv_ulice>Bul. Despota Stefana</ob:naziv_ulice>
        <ob:broj_ulice>7</ob:broj_ulice>
        <ob:grad>Novi Sad</ob:grad>
        <ob:postanski_broj>21000</ob:postanski_broj>
      </ob:adresa>
    </ob:podaci_o_podnosiocu>
  </ob:opste_informacije>
  <ob:naslov>Naslov obavestenja</ob:naslov>
  <ob:podnaslov>Podnaslov obavestenja</ob:podnaslov>
  <ob:telo>
    <ob:godina>2001</ob:godina>
    <ob:opis>Opis trazene informacije</ob:opis>
    <ob:datum>
      <ob:dan>---01</ob:dan>
      <ob:mesec>--01</ob:mesec>
      <ob:godina>2001</ob:godina>
    </ob:datum>
    <ob:vreme>12:00:00</ob:vreme>
    <ob:od>12:00:00</ob:od>
    <ob:do>12:00:00</ob:do>
    <ob:adresa_organa>
      <ob:naziv_ulice>Bul. Despota Stefana</ob:naziv_ulice>
      <ob:broj_ulice>12</ob:broj_ulice>
      <ob:broj_kancelarije>12</ob:broj_kancelarije>
    </ob:adresa_organa>
    <ob:iznos>1200.00</ob:iznos>
  </ob:telo>
  <ob:dostavljeno>Imenovanom</ob:dostavljeno>
</ob:obavestenje>

=== mirkovana/XML_i_Web_servisi_tim9/demo/data/Obavestenje1.xml
<?xml version="1.0" encoding="UTF-8"?>
<obavestenje:obavestenje xmlns:obavestenje="https://www.obavestenje.rs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.obavestenje.rs Obavestenje.xsd ">
  <obavestenje:opste_informacije>
    <obavestenje:podaci_o_organu>
      <obavestenje:naziv>obavestenje:naziv</obavestenje:naziv>
      <obavestenje:sediste>obavestenje:sediste</obavestenje:sediste>
    </obavestenje:podaci_o_organu>
    <obavestenje:broj_predmeta>obavestenje:broj_predmeta</obavestenje:broj_predmeta>
    <obavestenje:datum>
      <obavestenje:dan>---01</obavestenje:dan>
      <obavestenje:mesec>--01</obavestenje:mesec>
      <obavestenje:godina>2001</obavestenje:godina>
    </obavestenje:datum>
    <obavestenje:podaci_o_podnosiocu>
      <obavestenje:ime>obavestenje:ime</obavestenje:ime>
      <obavestenje:prezime>obavestenje:prezime</obavestenje:prezime>
      <obavestenje:naziv>obavestenje:naziv</obavestenje:naziv>
      <obavestenje:adresa>
        <obavestenje:ulica>obavestenje:ulica</obavestenje:ulica>
        <obavestenje:broj_ulice>obavestenje:broj_ulice</obavestenje:broj_ulice>
        <obavestenje:grad>obavestenje:grad</obavestenje:grad>
        <obavestenje:postanski_broj>1</obavestenje:postanski_broj>
      </obavestenje:adresa>
    </obavestenje:podaci_o_podnosiocu>
  </obavestenje:opste_informacije>
  <obavestenje:naslov>obavestenje:naslov</obavestenje:naslov>
  <obavestenje:podnaslov>obavestenje:podnaslov</obavestenje:podnaslov>
  <obavestenje:telo>
    <obavestenje:godina>2001</obavestenje:godina>
    <obavestenje:opis>obavestenje:opis</obavestenje:opis>
    <obavestenje:datum>
      <obavestenje:dan>---01</obavestenje:dan>
      <obavestenje:mesec>--01</obavestenje:mesec>
      <obavestenje:godina>2001</obavestenje:godina>
    </obavestenje:datum>
    <obavestenje:vreme>12:00:00</obavestenje:vreme>
    <obavestenje:od>12:00:00</obavestenje:od>
    <obavestenje:do>12:00:00</obavestenje:do>
    <obavestenje:adresa_organa>
      <obavestenje:naziv_ulice>obavestenje:naziv_ulice</obavestenje:naziv_ulice>
      <obavestenje:broj_ulice>obavestenje:broj_ulice</obavestenje:broj_ulice>
      <obavestenje:broj_kancelarije>1</obavestenje:broj_kancelarije>
    </obavestenje:adresa_organa>
    <obavestenje:iznos>0.0</obavestenje:iznos>
  </obavestenje:telo>
  <obavestenje:dostavljeno>Imenovanom</obavestenje:dostavljeno>
</obavestenje:obavestenje>
