=== mirkovana/XML_i_Web_servisi_tim9/demo/data/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/zahtev" xmlns:za="http://www.projekat.org/zahtev"
    xmlns:pred="http://www.projekat.org/predicate/">

    <xs:element name="zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="za:institucija"/>
                <xs:element ref="za:naslov" minOccurs="0"/>
                <xs:element ref="za:tekst_zahteva" minOccurs="1"/>
                <xs:element name="mesto_datum">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element ref="za:mesto"/>
                            <xs:element ref="za:datum"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="za:podnosilac"/>
                <xs:element minOccurs="0" name="footer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="reference">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="username" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="datum" type="za:TDatum" use="required"/>
            <xs:attribute form="unqualified" name="institucijaNaziv" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="institucija">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="naziv">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="za:mesto"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="naslov" type="za:naslovi">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
    </xs:element>
    <xs:element name="tekst_zahteva">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="uvod" minOccurs="0">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="zakon" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" name="clan">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="stav">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="tacka">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="1" name="naziv">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="glasnik">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="za:lista"/>
                <xs:element name="informacije">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mesto">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="2"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="datum">
        <xs:annotation>
            <xs:documentation>Datum formata dd.mm.yyyy.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="za:TDatum">
                    <xs:attribute name="property" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="podnosilac">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="osoba" type="za:osoba"/>
                <xs:element name="adresa">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="drugi_podaci">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="potpis">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="naslovi">
        <xs:simpleContent>
            <xs:extension base="xs:string"> </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:attribute default="false" name="checked" type="xs:boolean"/>
    <xs:attribute name="id">
        <xs:simpleType>
            <xs:restriction base="xs:int">
                <xs:minInclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:element name="stavka">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="za:checked" use="required"/>
                    <xs:attribute ref="za:id" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="osoba">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="ime" nillable="false">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="prezime" nillable="false">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="username">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="lista">
        <xs:complexType mixed="false">
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="stavka">
                    <xs:complexType mixed="true">
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:element minOccurs="0" ref="za:lista"/>
                            <xs:element minOccurs="0" ref="za:drugi_nacin"/>
                        </xs:sequence>
                        <xs:attribute ref="za:id" use="required"/>
                        <xs:attribute ref="za:checked" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="drugi_nacin">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="2"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:simpleType name="TDatum">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}[.]"/>
            <xs:length value="11"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/project/bin/src/main/resources/documents/zahtev.xml
<?xml version="1.0" encoding="UTF-8"?>
<za:zahtev 
    xmlns ="http://www.projekat.org/zahtev"
    xmlns:za="http://www.projekat.org/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.projekat.org/zahtev zahtev.xsd"
    id="0"
    username="username"
    datum="00.00.0000."
    institucija="nazivinstitucije">
    <za:institucija>
        <za:naziv>naziv0</za:naziv> u <za:mesto>mesto0</za:mesto>
    </za:institucija>
    <za:naslov za:nivo="4" za:stil="bold">Zahtev za pristupanje informacijama</za:naslov>
    <za:tekst_zahteva>
        <za:uvod>
            Na osnovu 
            <za:zakon>
                <za:clan>člana 15.</za:clan>
                <za:stav>st. 1.</za:stav>
                <za:naziv>Zakona o slobodnom pristupu informacijama od javnog značaja </za:naziv>
                <za:glasnik>(„Službeni glasnik RS“, br. 120/04, 54/07, 104/09 i 36/10)</za:glasnik>
            </za:zakon>, 
            od gore navedenog organa zahtevam:*
        </za:uvod>
        <za:lista>
            <za:stavka za:checked="false" za:id="1">obaveštenje da li poseduje traženu informaciju;</za:stavka>
            <za:stavka za:checked="false" za:id="2">uvid u dokument koji sadrži traženu informaciju;</za:stavka>
            <za:stavka za:checked="false" za:id="3">kopiju dokumenta koji sadrži traženu informaciju;</za:stavka>
            <za:stavka za:checked="false" za:id="4">
                dostavljanje kopije dokumenta koji sadrži traženu informaciju:**
                <za:lista>
                    <za:stavka za:checked="false" za:id="5">поштом</za:stavka>
                    <za:stavka za:checked="false" za:id="6">elektronskom postom</za:stavka>
                    <za:stavka za:checked="false" za:id="7">faksom</za:stavka>
                    <za:stavka  za:checked="false" za:id="8">na drugi nacin***: 
                        <za:drugi_nacin>dajshkdandaskla</za:drugi_nacin>
                    </za:stavka>
                </za:lista>
            </za:stavka>
        </za:lista>
        Ovaj zahtev se odnosi na sledece informacije:
        <za:informacije>
            ahda hahd ua dhajdh ah dlakhdah alsh dka 
        </za:informacije>
    </za:tekst_zahteva>
    <za:mesto_datum>
        U <za:mesto>mesto1</za:mesto> dana
        <za:datum>10.10.2020.</za:datum> godine
    </za:mesto_datum>
    <za:podnosilac>
        <za:osoba>
            <za:ime>ime0</za:ime>
            <za:prezime>prezime0</za:prezime>
        </za:osoba>
        <za:adresa>adresa0</za:adresa>
        <za:drugi_podaci>drugiPodaci0</za:drugi_podaci>
        <za:potpis>potpis0</za:potpis>
    </za:podnosilac>
    <za:footer>
        <za:reference>*U kućici označiti koja zakonska prava na pristup informacijama želite da ostvarite.</za:reference>
        <za:reference>**U kućici označiti način dostavljanja kopije dokumenata.</za:reference>
        <za:reference>***Kada zahtevate drugi način dostavljanja obavezno upisati koji način dostavljanja zahtevate.</za:reference>
    </za:footer>
</za:zahtev>

=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/zahtevE.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev 
    xmlns="http://www.projekat.org/zahtev"
    xmlns:za="http://www.projekat.org/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.projekat.org/zahtev zahtev.xsd">
    <institucija>
        <naziv></naziv> u <mesto></mesto>
    </institucija>
    <naslov za:nivo="4" za:stil="bold">Zahtev za pristupanje informacijama</naslov>
    <tekst_zahteva>
        <uvod>
            Na osnovu 
            <zakon>
                <clan>člana 15.</clan>
                <stav>st. 1.</stav>
                <naziv>Zakona o slobodnom pristupu informacijama od javnog značaja </naziv>
                <glasnik>(„Službeni glasnik RS“, br. 120/04, 54/07, 104/09 i 36/10)</glasnik>
            </zakon>, 
            od gore navedenog organa zahtevam:*
        </uvod>
        <lista>
            <stavka za:checked="false" za:id="1">obaveštenje da li poseduje traženu informaciju;</stavka>
            <stavka za:checked="false" za:id="2">uvid u dokument koji sadrži traženu informaciju;</stavka>
            <stavka za:checked="false" za:id="3">kopiju dokumenta koji sadrži traženu informaciju;</stavka>
            <stavka za:checked="false" za:id="4">
                dostavljanje kopije dokumenta koji sadrži traženu informaciju:**
                <lista>
                    <stavka za:checked="false" za:id="5">поштом</stavka>
                    <stavka za:checked="false" za:id="6">elektronskom postom</stavka>
                    <stavka za:checked="false" za:id="7">faksom</stavka>
                    <stavka  za:checked="false" za:id="8">na drugi nacin***: 
                        <drugi_nacin></drugi_nacin>
                    </stavka>
                </lista>
            </stavka>
        </lista>
        Ovaj zahtev se odnosi na sledece informacije:
        <informacije>
        </informacije>
    </tekst_zahteva>
    <mesto_datum>
        U <mesto></mesto> dana
        <datum></datum> godine
    </mesto_datum>
    <podnosilac>
        <osoba>
            <ime></ime>
            <prezime></prezime>
        </osoba>
        <adresa></adresa>
        <drugi_podaci></drugi_podaci>
        <potpis></potpis>
    </podnosilac>
    <footer>
        <reference>*U kućici označiti koja zakonska prava na pristup informacijama želite da ostvarite.</reference>
        <reference>**U kućici označiti način dostavljanja kopije dokumenata.</reference>
        <reference>***Kada zahtevate drugi način dostavljanja obavezno upisati koji način dostavljanja zahtevate.</reference>
    </footer>
</zahtev>

=== mirkovana/XML_i_Web_servisi_tim9/organvlasti/src/main/resources/documents/zahtev.xml
<?xml version="1.0" encoding="UTF-8"?>
<za:zahtev 
    xmlns ="http://www.projekat.org/zahtev"
    xmlns:za="http://www.projekat.org/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.projekat.org/predicate/"
    about="http://www.projekat.org/zahtev/aa54057c188c-2021"
    xsi:schemaLocation="http://www.projekat.org/zahtev zahtev.xsd"
    broj="aa54057c188c-2021"
    username="username"
    datum="00.00.0000." 
    institucijaNaziv="nazivinstitucije">
    <za:institucija>
        <za:naziv xmlns:za ="http://www.projekat.org/zahtev" property="pred:nazivInstitucije">naziv0</za:naziv> u <za:mesto>mesto0</za:mesto>
    </za:institucija>
    <za:tekst_zahteva>
        <za:lista>
            <za:stavka za:checked="false" za:id="1">obaveštenje da li poseduje traženu informaciju;</za:stavka>
            <za:stavka za:checked="false" za:id="2">uvid u dokument koji sadrži traženu informaciju;</za:stavka>
            <za:stavka za:checked="false" za:id="3">kopiju dokumenta koji sadrži traženu informaciju;</za:stavka>
            <za:stavka za:checked="false" za:id="4">
                dostavljanje kopije dokumenta koji sadrži traženu informaciju:**
                <za:lista>
                    <za:stavka za:checked="false" za:id="5">поштом</za:stavka>
                    <za:stavka za:checked="false" za:id="6">elektronskom postom</za:stavka>
                    <za:stavka za:checked="false" za:id="7">faksom</za:stavka>
                    <za:stavka  za:checked="false" za:id="8">na drugi nacin***: 
                        <za:drugi_nacin>dajshkdandaskla</za:drugi_nacin>
                    </za:stavka>
                </za:lista>
            </za:stavka>
        </za:lista>
        <za:informacije xmlns:za ="http://www.projekat.org/zahtev" property="pred:informacije">
            ahda hahd ua dhajdh ah dlakhdah alsh dka 
        </za:informacije>
    </za:tekst_zahteva>
    <za:mesto_datum>
        <za:mesto>mesto1</za:mesto>
        <za:datum xmlns:za ="http://www.projekat.org/zahtev" property="pred:datum">10.10.2020.</za:datum> godine
    </za:mesto_datum>
    <za:podnosilac>
        <za:osoba> 
            <za:ime xmlns:za ="http://www.projekat.org/zahtev" property="pred:ime">ime0</za:ime>
            <za:prezime xmlns:za ="http://www.projekat.org/zahtev" property="pred:prezime">prezime0</za:prezime>
            <za:username xmlns:za ="http://www.projekat.org/zahtev" property="pred:username">username</za:username>
        </za:osoba>
        <za:adresa>adresa0</za:adresa>
        <za:drugi_podaci>drugiPodaci0</za:drugi_podaci>
        <za:potpis>potpis0</za:potpis>
    </za:podnosilac>
</za:zahtev>
