=== mirkovana/XML_i_Web_servisi_tim9/demo/data/zalbazbogcutanjacir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/zalbaCutanja"
    xmlns:zc="http://www.ftn.uns.ac.rs/zalbaCutanja">
    <xs:element name="zalba_cutanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naslov">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="1000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="podaci_o_povereniku" type="zc:TPravno_lice"/>
                <xs:element name="telo_zalbe" type="zc:Ttelo_zalbe"/>
                <xs:element name="podaci_o_podnosiocu_zalbe" type="zc:TFizicko_lice"/>
                <xs:element name="podaci_o_mestu_i_datumu_podnosenja_zalbe" type="zc:Tmesto_datum"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grad">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="zc:adresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="zc:TLice">
                <xs:sequence>
                    <xs:element name="naziv_poverenika">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="500"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="zc:TLice">
                <xs:sequence>
                    <xs:element name="ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="2"/>
                                <xs:maxLength value="15"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="2"/>
                                <xs:maxLength value="20"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="drugi_podaci_za_kontakt">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="50"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType mixed="true" name="Ttelo_zalbe">
        <xs:sequence>
            <xs:element name="poziv_na_zakon" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="naziv_organa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="razlozi" type="zc:Trazlozi"/>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="podaci_o_zahtevu_i_informaciji">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="1000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="napomena">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tmesto_datum">
        <xs:sequence>
            <xs:element name="mesto">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Trazlozi">
        <xs:choice>
            <xs:element name="nije_postupio"/>
            <xs:element name="nije_postupio_u_celosti"/>
            <xs:element name="nije_postupio_u_zakonskom_roku"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/demo/data/zalbazbogcutanjacir.xml
<?xml version="1.0" encoding="UTF-8"?>
<zc:zalba_cutanje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zc="http://www.ftn.uns.ac.rs/zalbaCutanja" xsi:schemaLocation="http://www.ftn.uns.ac.rs/zalbaCutanja zalbazbogcutanjacir.xsd ">
  <zc:naslov>zc:naslov</zc:naslov>
  <zc:podaci_o_povereniku>
    <zc:adresa>
      <zc:grad>zc:grad</zc:grad>
      <zc:ulica>zc:ulica</zc:ulica>
      <zc:broj>1</zc:broj>
    </zc:adresa>
    <zc:naziv_poverenika>zc:naziv_poverenika</zc:naziv_poverenika>
  </zc:podaci_o_povereniku>
  <zc:telo_zalbe>
    <zc:poziv_na_zakon>zc:poziv_na_zakon</zc:poziv_na_zakon>
    <zc:naziv_organa>zc:naziv_organa</zc:naziv_organa>
    <zc:razlozi>
      <zc:nije_postupio/>
    </zc:razlozi>
    <zc:datum>2001-01-01</zc:datum>
    <zc:podaci_o_zahtevu_i_informaciji>zc:podaci_o_zahtevu_i_informaciji</zc:podaci_o_zahtevu_i_informaciji>
    <zc:napomena>zc:napomena</zc:napomena>
  </zc:telo_zalbe>
  <zc:podaci_o_podnosiocu_zalbe>
    <zc:adresa>
      <zc:grad>zc:grad</zc:grad>
      <zc:ulica>zc:ulica</zc:ulica>
      <zc:broj>1</zc:broj>
    </zc:adresa>
    <zc:ime>zc:ime</zc:ime>
    <zc:prezime>zc:prezime</zc:prezime>
    <zc:drugi_podaci_za_kontakt>zc:drugi_podaci_za_kontakt</zc:drugi_podaci_za_kontakt>
  </zc:podaci_o_podnosiocu_zalbe>
  <zc:podaci_o_mestu_i_datumu_podnosenja_zalbe>
    <zc:mesto>zc:mesto</zc:mesto>
    <zc:datum>2001-01-01</zc:datum>
  </zc:podaci_o_mestu_i_datumu_podnosenja_zalbe>
</zc:zalba_cutanje>
