=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/obavestenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/obavestenje"
    xmlns:ob="http://www.projekat.org/obavestenje">
    <xs:element name="obavestenje">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="opste_informacije" type="ob:Topste_informacije"> </xs:element>
                <xs:element name="naslov" type="ob:TNaslov"> </xs:element>
                <xs:element name="podnaslov" type="ob:TNaslov"> </xs:element>
                <xs:element name="telo" type="ob:Ttelo_obavestenja" maxOccurs="1" minOccurs="1"> </xs:element>
                <xs:element name="dostavljeno" maxOccurs="unbounded">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Imenovanom"/>
                            <xs:enumeration value="Arhivi"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="potpis_rukovodioca">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="Tadresa" mixed="true">
        <xs:sequence>
            <xs:element name="naziv_ulice">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj_ulice">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="naziv_grada">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tadresa_organa" mixed="true">
        <xs:complexContent>
            <xs:extension base="ob:Tadresa">
                <xs:sequence>
                    <xs:element name="broj_kancelarije">
                        <xs:simpleType>
                            <xs:restriction base="xs:int">
                                <xs:minInclusive value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="Tadresa_podnosioca" mixed="true">
        <xs:complexContent mixed="true">
            <xs:extension base="ob:Tadresa">
                <xs:sequence>
                    <xs:element name="grad" minOccurs="0">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="postanski_broj">
                        <xs:simpleType>
                            <xs:restriction base="xs:int">
                                <xs:minInclusive value="11000"/>
                                <xs:maxInclusive value="38999"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="Ttelo_obavestenja" mixed="true">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="godina" type="xs:gYear" minOccurs="0"/>
            <xs:element name="opis_trazene_informacije" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="ob:TDatum" minOccurs="0"/>
            <xs:element name="vreme" type="xs:time" minOccurs="0"/>
            <xs:element name="od" type="xs:time" minOccurs="0"/>
            <xs:element name="do" type="xs:time" minOccurs="0"/>
            <xs:element name="adresa_organa" type="ob:Tadresa_organa" minOccurs="0"/>
            <xs:element minOccurs="0" name="troskovi">
                <xs:complexType mixed="false">
                    <xs:sequence maxOccurs="unbounded" minOccurs="1">
                        <xs:element name="stavka">
                            <xs:complexType mixed="true">
                                <xs:sequence>
                                    <xs:element name="naziv_troska" type="xs:string"/>
                                    <xs:element name="cena" type="xs:double"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="ziro_racun">
                <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:element name="primalac" type="xs:string"/>
                        <xs:element name="br_racuna">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[0-9]{3}-[0-9]{6}-[0-9]{3}-[0-9]{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="poziv_na_broj">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="ukupni_trosak">
                <xs:simpleType>
                    <xs:restriction base="xs:double">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="zakon" type="ob:TZakon"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Torgan">
        <xs:sequence>
            <xs:element name="naziv">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="sediste">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tpodnosilac">
        <xs:sequence>
            <xs:element name="ime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="prezime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="naziv_zahteva">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="adresa" type="ob:Tadresa_podnosioca"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Topste_informacije">
        <xs:sequence>
            <xs:element name="podaci_o_organu" type="ob:Torgan"/>
            <xs:element name="broj_predmeta">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                        <xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}/[0-9]{4}-[0-9]{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="ob:TDatum"/>
            <xs:element name="podaci_o_podnosiocu" type="ob:Tpodnosilac"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TDatum">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}[.]"/>
            <xs:length value="11"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TNaslov">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="ob:nivo"/>
                <xs:attribute ref="ob:stil"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:attribute name="nivo" type="ob:nivoi">
        <xs:annotation>
            <xs:documentation>atribut koji predstavlja nivo naslova ili liste</xs:documentation>
        </xs:annotation>
    </xs:attribute>
    <xs:attribute name="stil" type="xs:string">
        <xs:annotation>
            <xs:documentation>atribut kojim se defini[e stil odre]eneog elementa</xs:documentation>
        </xs:annotation>
    </xs:attribute>
    <xs:simpleType name="nivoi">
        <xs:annotation>
            <xs:documentation>Tip koji predstalvja nivoe 1-6</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="6"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TZakon">
        <xs:sequence>
            <xs:element minOccurs="0" name="clan" type="xs:string"> </xs:element>
            <xs:element minOccurs="0" name="stav" type="xs:string"> </xs:element>
            <xs:element minOccurs="0" name="tacka" type="xs:string"> </xs:element>
            <xs:element minOccurs="1" name="naziv" type="xs:string"> </xs:element>
            <xs:element minOccurs="0" name="glasnik" type="xs:string"> </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== mirkovana/XML_i_Web_servisi_tim9/projectsoap/src/main/resources/documents/obavestenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<ob:obavestenje 
  xmlns="http://www.projekat.org/obavestenje" 
  xmlns:ob="http://www.projekat.org/obavestenje" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:pred="http://www.projekat.org/predicate/"
  about="http://www.projekat.org/obavestenje/aa54057c188c-2021"
  xsi:schemaLocation="http://www.projekat.org/obavestenje Obavestenje.xsd"
  broj="aa54057c188c-2021" 
  username="username"  
  datum="00.00.0000."
  organVlastiUsername="organVlastiUsername">
  <ob:opste_informacije>
    <ob:podaci_o_organu>
      <ob:naziv xmlns:ob="http://www.projekat.org/obavestenje" property="pred:nazivOrgana">Naziv organa</ob:naziv>
      <ob:sediste xmlns:ob="http://www.projekat.org/obavestenje" property="pred:sedisteOrgana">Novi Sad</ob:sediste>
    </ob:podaci_o_organu>  
    <ob:broj_predmeta xmlns:ob="http://www.projekat.org/obavestenje" property="pred:brojPredmeta">aa54057c188c-2021</ob:broj_predmeta>
    <ob:datum xmlns:ob="http://www.projekat.org/obavestenje" property="pred:datum">10.10.2020.</ob:datum>
    <ob:podaci_o_podnosiocu>
      <ob:ime xmlns:ob="http://www.projekat.org/obavestenje" property="pred:ime">Imenko</ob:ime>
      <ob:prezime xmlns:ob="http://www.projekat.org/obavestenje" property="pred:prezime">Prezimenko</ob:prezime>
      <ob:adresa>
        <ob:naziv_ulice>Bul Despota Stefana</ob:naziv_ulice>
        <ob:grad>Novi Sad</ob:grad>
      </ob:adresa> 
    </ob:podaci_o_podnosiocu>
  </ob:opste_informacije>
  <ob:telo>
    <ob:godina>2001</ob:godina>
    <ob:opis>Neki opis</ob:opis>
     <ob:datum>10.10.2020.</ob:datum>
    <ob:vreme>12:00:00</ob:vreme>
    <ob:od>12:00:00</ob:od>
    <ob:do>12:00:00</ob:do>
    <ob:adresa_organa>
      <ob:naziv_ulice>Mire Popare</ob:naziv_ulice>
      <ob:broj_ulice>25</ob:broj_ulice>
      <ob:broj_kancelarije>12</ob:broj_kancelarije>
    </ob:adresa_organa>
    <ob:iznos>1200.00</ob:iznos>
  </ob:telo>
  <ob:potpis>Potpis</ob:potpis>
</ob:obavestenje>

=== mirkovana/XML_i_Web_servisi_tim9/organvlasti/src/main/resources/documents/Obavestenje12.xml
<?xml version="1.0" encoding="UTF-8"?>
<ob:obavestenje about="" broj="" datum="10.10.2020." organVlastiUsername="" username="" xmlns:ob="http://www.projekat.org/obavestenje" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.projekat.org/obavestenje Obavestenje.xsd ">
  <ob:opste_informacije>
    <ob:podaci_o_organu>
      <ob:naziv property="">ob:naziv</ob:naziv>
      <ob:sediste property="">ob:sediste</ob:sediste>
    </ob:podaci_o_organu>
    <ob:broj_predmeta property="">ob:broj_predmeta</ob:broj_predmeta>
    <ob:datum property="">ob:datum</ob:datum>
    <ob:podaci_o_podnosiocu>
      <ob:ime property="">ob:ime</ob:ime>
      <ob:prezime property="">ob:prezime</ob:prezime>
      <ob:adresa>
        <ob:naziv_ulice>ob:naziv_ulice</ob:naziv_ulice>
        <ob:grad>ob:grad</ob:grad>
      </ob:adresa>
    </ob:podaci_o_podnosiocu>
  </ob:opste_informacije>
  <ob:naslov>ob:naslov</ob:naslov>
  <ob:podnaslov>ob:podnaslov</ob:podnaslov>
  <ob:telo>
    <ob:godina>2001</ob:godina>
    <ob:opis>ob:opis</ob:opis>
    <ob:datum>10.10.2020.</ob:datum>
    <ob:vreme>12:00:00</ob:vreme>
    <ob:od>12:00:00</ob:od>
    <ob:do>12:00:00</ob:do>
    <ob:adresa_organa>
      <ob:naziv_ulice>ob:naziv_ulice</ob:naziv_ulice>
      <ob:broj_kancelarije>1</ob:broj_kancelarije>
    </ob:adresa_organa>
    <ob:iznos>1220.00</ob:iznos>
  </ob:telo>
  <ob:dostavljeno>Imenovanom</ob:dostavljeno>
  <ob:potpis>ob:potpis</ob:potpis>
</ob:obavestenje>

=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/obavestenjeE.xml
<?xml version="1.0" encoding="UTF-8"?>
<obavestenje
    xmlns="http://www.projekat.org/obavestenje"
    xmlns:ob="http://www.projekat.org/obavestenje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.projekat.org/obavestenje obavestenje.xsd">
    <opste_informacije>
        <podaci_o_organu>
            <naziv></naziv>
            <sediste></sediste>
        </podaci_o_organu>
        <broj_predmeta></broj_predmeta>
        <datum></datum> 
        <podaci_o_podnosiocu>
            <ime></ime>
            <prezime></prezime>
            <naziv_zahteva></naziv_zahteva>
            <adresa>
                <naziv_ulice></naziv_ulice>
                <broj_ulice></broj_ulice>
                <naziv_grada></naziv_grada>
                <postanski_broj></postanski_broj>
            </adresa>
        </podaci_o_podnosiocu>
    </opste_informacije>
    <naslov ob:nivo="4" ob:stil="bold">O B A V E Š T E Nj E</naslov>
    <podnaslov ob:nivo="2" ob:stil="bold">
        o stavljanju na uvid dokumenta koji sadrži
        traženu informaciju i o izradi kopije
    </podnaslov>
    <telo>
        Na osnovu         
        <zakon>
            <clan>člana 16.</clan>
            <stav>st. 1.</stav>
            <naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</naziv>
        </zakon>
        , postupajući po vašem zahtevu za slobodan pristup informacijama od
        <godina></godina>god.,
        kojim ste trazili uvid u dokument/e sa informacijama o / u vezi sa:
        <opis_trazene_informacije></opis_trazene_informacije> 
        obaveštavamo vas da dana
        <datum></datum>
        , u 
        <vreme></vreme> časova, odnosno u vremenu od 
        <od></od>
        do 
        <do></do>
        časova, u prostorijama organa u 
        <adresa_organa>
            <naziv_ulice></naziv_ulice> 
            <broj_ulice></broj_ulice>
            <naziv_grada> Sadu</naziv_grada>
            kancelarija br.
            <broj_kancelarije></broj_kancelarije>
        </adresa_organa>
        možete izvršiti uvid u dokument/e u kome je sadržana tražena informacija.
        Tom prilikom, na vaš zahtev, može vam se izdati i kopija dokumenta sa traženom informacijom.
        Troškovi su utvrđeni 
        <zakon>
            <naziv>Uredbom Vlade Republike Srbije</naziv>
            <glasnik>(„Sl. glasnik RS“, br. 8/06)</glasnik>
        </zakon>
        , i to: 
        <troskovi>
            <stavka>
                <naziv_troska>kopija strane A4 formata</naziv_troska>
                iznosi
                <cena>3</cena>dinara,
            </stavka>
            <stavka>
                <naziv_troska>A3 formata</naziv_troska>
                <cena>6</cena> dinara,
            </stavka>
            <stavka>
                <naziv_troska>CD</naziv_troska>
                <cena>35</cena> dinara,
            </stavka>
            <stavka>
                <naziv_troska>diskete</naziv_troska>
                <cena>20</cena> dinara,
            </stavka>    
            <stavka>
                <naziv_troska>DVD</naziv_troska>
                <cena>40</cena> dinara,
            </stavka>
        </troskovi>
        Iznos ukupnih troškova izrade kopije dokumenta po vašem zahtevu iznosi 
        <ukupni_trosak>500.00</ukupni_trosak> 
        dinara i uplaćuje se na žiro-račun 
        <ziro_racun>
            <primalac>Budžeta Republike Srbije </primalac>
            br. <br_racuna>840-742328-843-30</br_racuna>,
            s pozivom na broj <poziv_na_broj>97</poziv_na_broj>
        </ziro_racun> 
        - oznaka šifre opštine/grada gde se nalazi organ vlasti 
        (iz Pravilnika o uslovima i načinu vođenja računa – „Sl. glasnik RS“, 20/07... 40/10).
    </telo>
    Dostavljeno:
    <dostavljeno>Imenovanom</dostavljeno>
    <dostavljeno>Arhivi</dostavljeno>
    <potpis_rukovodioca>
        potpis
    </potpis_rukovodioca>
</obavestenje>

=== mirkovana/XML_i_Web_servisi_tim9/XMLprojekat/data/obavestenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<obavestenje
    xmlns="http://www.projekat.org/obavestenje"
    xmlns:ob="http://www.projekat.org/obavestenje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.projekat.org/obavestenje obavestenje.xsd">
    <opste_informacije>
        <podaci_o_organu>
            <naziv>Neki organ</naziv>
            <sediste>Novi Sad</sediste>
        </podaci_o_organu>
        <broj_predmeta>123-45-6789/1234-56</broj_predmeta>
        <datum>10.10.2010.</datum> 
        <podaci_o_podnosiocu>
            <ime>Neko</ime>
            <prezime>Prezimenko</prezime>
            <naziv>asdasdasd</naziv>
            <adresa>
                <ulica>Neka ulica</ulica>
                <broj_ulice>12</broj_ulice>
                <grad>Neki grad</grad>
                <postanski_broj>11111</postanski_broj>
            </adresa>
        </podaci_o_podnosiocu>
    </opste_informacije>
    <naslov ob:nivo="4" ob:stil="bold">O B A V E Š T E Nj E</naslov>
    <podnaslov ob:nivo="2" ob:stil="bold">
        o stavljanju na uvid dokumenta koji sadrži
        traženu informaciju i o izradi kopije
    </podnaslov>
    <telo> 
        Na osnovu 
        <zakon>
            <clan>člana 16.</clan>
            <stav>st. 1.</stav>
            <naziv>Zakona o slobodnom pristupu informacijama od javnog značaja</naziv>
        </zakon> 
        , postupajući po vašem zahtevu za slobodan pristup informacijama od
        <god>2010</god>год., 
        kojim ste trazili uvid u dokument/e sa informacijama o / u vezi sa:
        <opis_trazene_info>_____opis trazene informaicje______</opis_trazene_info> 
        obaveštavamo vas da dana
        <datum>10.10.2010.</datum>
        , u 
        <vreme>10:00:00</vreme> časova, odnosno u vremenu od 
        <od>10:00:00</od>
        do 
        <do>11:00:00</do>
        časova, u prostorijama organa u 
        <adresa_organa>
            <naziv_grada>Novom Sadu</naziv_grada>
            ul. <naziv_ulice>asdasd</naziv_ulice> 
            , бр. <broj_ulice>2</broj_ulice> 
            kancelarija br. <broj_kancelarije>10</broj_kancelarije>
        </adresa_organa>
        možete izvršiti uvid u dokument/e u kome je sadržana tražena informacija.
        Tom prilikom, na vaš zahtev, može vam se izdati i kopija dokumenta sa traženom informacijom.

        Troškovi su utvrđeni 
        <zakon>
            <naziv>Uredbom Vlade Republike Srbije</naziv>
            <glasnik>(„Sl. glasnik RS“, br. 8/06)</glasnik>
        </zakon>
        , i to: 
        <troskovi>
            <stavka>
                <naziv_troska>kopija strane A4 formata</naziv_troska>
                iznosi
                <cena>3</cena>dinara,
            </stavka>
            <stavka>
                <naziv_troska>A3 formata</naziv_troska>
                <cena>6</cena> dinara,
            </stavka>
            <stavka>
                <naziv_troska>CD</naziv_troska>
                <cena>35</cena> dinara,
            </stavka>
            <stavka>
                <naziv_troska>diskete</naziv_troska>
                <cena>20</cena> dinara,
            </stavka>    
            <stavka>
                <naziv_troska>DVD</naziv_troska>
                <cena>40</cena> dinara,
            </stavka>
        </troskovi>
        Iznos ukupnih troškova izrade kopije dokumenta po vašem zahtevu iznosi 
        <ukupni_trosak>500.00</ukupni_trosak> 
        dinara i uplaćuje se na žiro-račun 
        <ziro_racun>
            <primalac>Budžeta Republike Srbije </primalac>
            br. <br_racuna>840-742328-843-30</br_racuna>,
            s pozivom na broj <poziv_na_broj>97</poziv_na_broj>
        </ziro_racun> 
        - oznaka šifre opštine/grada gde se nalazi organ vlasti 
        (iz Pravilnika o uslovima i načinu vođenja računa – „Sl. glasnik RS“, 20/07... 40/10).
    </telo>
    <dostavljeno>
        Dostavljeno:
        1.	Imenovanom
        2.	Arhivi
    </dostavljeno>
    <potpis_rukovodioca>
        potpis
    </potpis_rukovodioca>
</obavestenje>
